<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventService.Domain\EventService.Domain.csproj" />
    <ProjectReference Include="..\..\Shared.Contracts\Shared.Contracts.csproj" />
  </ItemGroup>

</Project>
