<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NotificationService.Domain\NotificationService.Domain.csproj" />
    <ProjectReference Include="..\..\Shared.Contracts\Shared.Contracts.csproj" />
  </ItemGroup>

</Project>
